/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.106
 * Generated at: 2021-12-27 15:18:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addBook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>add book</title>\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js\"\n");
      out.write("\ttype=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jqueryyui/1.7.2/jquery.-ui-min.js\"\n");
      out.write("\ttype=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function(){\n");
      out.write("\n");
      out.write("\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl:\"BookServlet?action=getCategory\",\n");
      out.write("\t    type: \"get\",\n");
      out.write("\t    datatype:\"json\",\n");
      out.write("\t    success : function(responseJson){\n");
      out.write("\t    \t\n");
      out.write("\t    \n");
      out.write("\t    \tif(responseJson!=null){\n");
      out.write("\t    \t\t$.each(responseJson, function(index,obj){\n");
      out.write("\t    \t\t\t\n");
      out.write("\t    \t\t\tif(obj!=null){\n");
      out.write("\t    \t\t\t\t$(\"#category\").append(\n");
      out.write("\t    \t\t\t\t'<option value=\"'+obj.category+'\">'\n");
      out.write("\t    \t\t\t\t+obj.category+'</option>');\n");
      out.write("\t    \t\t\t\t\n");
      out.write("}\n");
      out.write("\t    \t\t});\t \n");
      out.write("\t    \t}\n");
      out.write("\t    }\n");
      out.write("});\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl:\"BookServlet?action=getPublisher\",\n");
      out.write("\t    type: \"get\",\n");
      out.write("\t    datatype:\"json\",\n");
      out.write("\t    success : function(responseJson){\n");
      out.write("\t    \tif(responseJson!=null){\n");
      out.write("\t    \t\t$.each(responseJson, function(index,obj){\n");
      out.write("\t    \t\t\t\n");
      out.write("\t    \t\t\tif(obj!=null){\n");
      out.write("\t    \t\t\t\t$(\"#publisher\").append(\n");
      out.write("\t    \t\t\t\t'<option value=\"'+obj.publisher+'\">'\n");
      out.write("\t    \t\t\t\t+obj.publisher+'</option>');\n");
      out.write("}\n");
      out.write("});\n");
      out.write("}\n");
      out.write("\t    }\n");
      out.write("\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("}); \n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function validate()\n");
      out.write("{\n");
      out.write("\tvar bname=document.getElementById(\"bookname\").value;\n");
      out.write("\tvar bprize=document.getElementById(\"bookprize\").value;\n");
      out.write("\tvar bauthor=document.getElementById(\"bookauthor\").value;\n");
      out.write("\tvar bquantity=document.getElementById(\"bookquantity\").value;\n");
      out.write("\tvar bdesc=document.getElementById(\"bookdesc\").value;\n");
      out.write("\tif(bname==\"\")\n");
      out.write("\t\t{\n");
      out.write("\t\tdocument.getElementById(\"ebookname\").innerHTML=\"please enter book name\";\n");
      out.write("\t     return false;\n");
      out.write("\t     }\n");
      out.write("\telse\n");
      out.write("\t\t{\n");
      out.write("\t\tdocument.getElementById(\"ebookname\").innerHTML=\"\";\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\tif(bprize==\"\")\n");
      out.write("\t\t{\n");
      out.write("\t\tdocument.getElementById(\"ebookprize\").innerHTML=\"please enter book prize\";\n");
      out.write("\t     return false;\n");
      out.write("\t     }\n");
      out.write("\telse\n");
      out.write("\t\t{\n");
      out.write("\t\tdocument.getElementById(\"ebookprize\").innerHTML=\"\";\n");
      out.write("\t\t}\n");
      out.write("\tif(bauthor==\"\")\n");
      out.write("\t{\n");
      out.write("\tdocument.getElementById(\"ebookauthor\").innerHTML=\"please enter book author\";\n");
      out.write("     return false;\n");
      out.write("     }\n");
      out.write("else\n");
      out.write("\t{\n");
      out.write("\tdocument.getElementById(\"ebookauthor\").innerHTML=\"\";\n");
      out.write("\t}\n");
      out.write("\tif(bquantity==\"\")\n");
      out.write("\t{\n");
      out.write("\tdocument.getElementById(\"ebookquantity\").innerHTML=\"please enter book quantity\";\n");
      out.write("     return false;\n");
      out.write("     }\n");
      out.write("else\n");
      out.write("\t{\n");
      out.write("\tdocument.getElementById(\"ebookquantity\").innerHTML=\"\";\n");
      out.write("\t}\n");
      out.write("\tif(bdesc==\"\")\n");
      out.write("\t{\n");
      out.write("\tdocument.getElementById(\"ebookdesc\").innerHTML=\"please enter  book Description\";\n");
      out.write("     return false;\n");
      out.write("     }\n");
      out.write("else\n");
      out.write("\t{\n");
      out.write("\tdocument.getElementById(\"ebookdesc\").innerHTML=\"\";\n");
      out.write("\t}\n");
      out.write("\treturn true;\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t}</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<center>\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<form  onsubmit=\"return validate()\" action=\"BookServlet\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("<h1><u><b>Add Book Details</b></u></h1>\n");
      out.write("<table  bOrders=\"1\">\n");
      out.write("<tr>\n");
      out.write("<th>Enter Book Name</th>\n");
      out.write("<th><input id=\"bookname\" type=\"text\" name=\"bookname\"></th>\n");
      out.write("<td> <span id=\"ebookname\" style=\"color:red\" ></span></td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<th>Enter Book Prize</th>\n");
      out.write("<th><input id=\"bookprize\" type=\"text\" name=\"bookprize\"></th>\n");
      out.write("<td><span id=\"ebookprize\" style=\"color:red\"></span></td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<th>Enter Book Author</th>\n");
      out.write("<th><input id=\"bookauthor\" type=\"text\" name=\"bookauthor\"></th>\n");
      out.write("<td><span id=\"ebookauthor\" style=\"color:red\"></span></td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<th>Enter Book Publisher</th>\n");
      out.write("<th>\n");
      out.write("<select name=\"publisher\" id=\"publisher\">\n");
      out.write("</select>\n");
      out.write("</th>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<th>Enter Book Category</th>\n");
      out.write("<th>\n");
      out.write("<select name=\"category\" id=\"category\">\n");
      out.write("\n");
      out.write("</select>\n");
      out.write("</th>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<th>Enter Book Quantity</th>\n");
      out.write("\n");
      out.write("<th><input id=\"bookquantity\" type=\"text\" name=\"bookquantity\"></th>\n");
      out.write("<td><span id=\"ebookquantity\" style=\"color:red\"></span></td>\n");
      out.write("\n");
      out.write("</th>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<th>Enter Book Description</th>\n");
      out.write("<th><input id=\"bookdesc\" type=\"text\" name=\"bookdesc\"></th>\n");
      out.write("<td><span id=\"ebookdesc\" style=\"color:red\"></span></td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<th>Book Image</th>\n");
      out.write("<th><input type=\"file\" size=300 name=\"bookImage\"></th>\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\n");
      out.write("<th><input type=\"reset\"  value=\"Clear\" name=\"\" ></th>\n");
      out.write("\n");
      out.write("<th><input type=\"submit\" value=\"Add\" name=\"action\"></th>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</form>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("</center>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
