/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.106
 * Generated at: 2021-12-26 08:45:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("   \n");
      out.write("<!DOCTYPE html> \n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>search</title>\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js\"\n");
      out.write("\ttype=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jqueryyui/1.7.2/jquery.-ui-min.js\"\n");
      out.write("\ttype=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function()\n");
      out.write("{\n");
      out.write("\t$(\"table\").hide();\n");
      out.write("\t$(\"button\").click(function(e)\n");
      out.write("\t{\n");
      out.write("\t\te.preventDefault();\n");
      out.write("\t\t var Bookname=$(\"#bookname\").val();\n");
      out.write("\t\t alert(\"hello:::\"+Bookname);\n");
      out.write("\t\t $.ajax({\n");
      out.write("\t\t\t url:\"BookServlet?action=searchByName&bookname=\"+Bookname,\n");
      out.write("\t         type:\"get\",\n");
      out.write("\t         data: Bookname,\n");
      out.write("\t         dataType:\"json\",\n");
      out.write("\t         \n");
      out.write("\t         success: function(responseJson){\n");
      out.write("\t        \t if(responseJson!=null)\n");
      out.write("\t        \t\t {\n");
      out.write("\t        \t\t alert(\"hhhhh\");\n");
      out.write("\t        \t\t $(\"tbody\").html(\"\");\n");
      out.write("\t        \t\t $.each(responseJson,function(index,obj){\n");
      out.write("\t        \t\t\t \n");
      out.write("\t        \t\t\t if(obj!=null)\n");
      out.write("\t        \t\t\t\t {\n");
      out.write("\t        \t\t\t\t $(\"table\").css(\"display\",\"block\");\n");
      out.write("\t        \t\t\t\t \n");
      out.write("\t        \t\t\t\t $(\"tbody\").append(\"<tr><td>\"+obj.bookId+\"<td>\");\n");
      out.write("\t        \t\t\t\t $(\"tbody\").append(\"<td>\"+obj.bookName+\"<td>\");\n");
      out.write("\t        \t\t\t\t $(\"tbody\").append(\"<td>\"+obj.prize+\"<td>\");\n");
      out.write("\t        \t\t\t\t $(\"tbody\").append(\"<td>\"+obj.authorName+\"<td>\");\n");
      out.write("\t        \t\t\t\t $(\"tbody\").append(\"<td>\"+obj.publisher+\"<td>\");\n");
      out.write("\t        \t\t\t\t $(\"tbody\").append(\"<td>\"+obj.bookDesc+\"<td>\");\n");
      out.write("\t        \t\t\t\t $(\"tbody\").append(\"<td>\"+obj.category+\"<td>\");\n");
      out.write("\t        \t\t\t\t $(\"tbody\").append(\"<td>\"+obj.quantity+\"<td></tr>\")\n");
      out.write("\t        \t\t\t\t \n");
      out.write("\t        \t\t\t\t }\n");
      out.write("\t        \t\t });\n");
      out.write("\t        \t\t \n");
      out.write("\t        \t\t \n");
      out.write("\t        \t\t \n");
      out.write("\t        \t\t }\n");
      out.write("\t        \t \n");
      out.write("\t        \t \n");
      out.write("\t        \t \n");
      out.write("\t         }\n");
      out.write("\t\t\t \n");
      out.write("\t\t });\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<center>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<h1><u><b>Search</b></u></h1>\n");
      out.write("<input type=\"text\" name=\"bookname\" id=\"bookname\">\n");
      out.write("<button>Search</button>\n");
      out.write("<form action=\"\" method=\"\" >\n");
      out.write("<table  bOrders=\"1\">\n");
      out.write("<tbody>\n");
      out.write("</tbody>\n");
      out.write("<thead>\n");
      out.write("<tr>\n");
      out.write("<td>Book Id</td>\n");
      out.write("<td>Book name</td>\n");
      out.write("<td>Price</td>\n");
      out.write("<td>Author</td>\n");
      out.write("<td>Publisher</td>\n");
      out.write("<td>Book Description</td>\n");
      out.write("<td>Category</td>\n");
      out.write("<td>Quantity</td>\n");
      out.write("</tr>\n");
      out.write("</thead>\n");
      out.write("\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write(" </form>\n");
      out.write("</center>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
