/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.106
 * Generated at: 2021-12-26 06:53:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.onlinebookstore.pojo.Book;

public final class updateBook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>update book</title>\r\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jqueryyui/1.7.2/jquery.-ui-min.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"BookServlet?action=getCategory\",\r\n");
      out.write("\t    type: \"get\",\r\n");
      out.write("\t    datatype:\"json\",\r\n");
      out.write("\t    success : function(responseJson){\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \talert(\"naina\");\r\n");
      out.write("\t    \tif(responseJson!=null){\r\n");
      out.write("\t    \t\t$.each(responseJson, function(index,obj){\r\n");
      out.write("\t    \t\t\t\r\n");
      out.write("\t    \t\t\tif(obj!=null){\r\n");
      out.write("\t    \t\t\t\t$(\"#category\").append(\r\n");
      out.write("\t    \t\t\t\t'<option value=\"'+obj.category+'\">'\r\n");
      out.write("\t    \t\t\t\t+obj.category+'</option>');\r\n");
      out.write("\t    \t\t\t\t\r\n");
      out.write("}\r\n");
      out.write("\t    \t\t});\t \r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"BookServlet?action=getPublisher\",\r\n");
      out.write("\t    type: \"get\",\r\n");
      out.write("\t    datatype:\"json\",\r\n");
      out.write("\t    success : function(responseJson){\r\n");
      out.write("\t    \tif(responseJson!=null){\r\n");
      out.write("\t    \t\t$.each(responseJson, function(index,obj){\r\n");
      out.write("\t    \t\t\t\r\n");
      out.write("\t    \t\t\tif(obj!=null){\r\n");
      out.write("\t    \t\t\t\t$(\"#publisher\").append(\r\n");
      out.write("\t    \t\t\t\t'<option value=\"'+obj.publisher+'\">'\r\n");
      out.write("\t    \t\t\t\t+obj.publisher+'</option>');\r\n");
      out.write("}\r\n");
      out.write("});\r\n");
      out.write("}\r\n");
      out.write("\t    }\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("}); \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function validate()\r\n");
      out.write("{   \r\n");
      out.write("\tvar bid=document.getElementById(\"bookid\").value;\r\n");
      out.write("\tvar bname=document.getElementById(\"bookname\").value;\r\n");
      out.write("\tvar bprize=document.getElementById(\"bookprize\").value;\r\n");
      out.write("\tvar bauthor=document.getElementById(\"bookauthor\").value;\r\n");
      out.write("\tvar bquantity=document.getElementById(\"bookquantity\").value;\r\n");
      out.write("\tvar bdesc=document.getElementById(\"bookdesc\").value;\r\n");
      out.write("\tif(bid==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\tdocument.getElementById(\"ebookid\").innerHTML=\"please enter book id\";\r\n");
      out.write("     return false;\r\n");
      out.write("     }\r\n");
      out.write("else\r\n");
      out.write("\t{\r\n");
      out.write("\tdocument.getElementById(\"ebookid\").innerHTML=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif(bname==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tdocument.getElementById(\"ebookname\").innerHTML=\"please enter book name\";\r\n");
      out.write("\t     return false;\r\n");
      out.write("\t     }\r\n");
      out.write("\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tdocument.getElementById(\"ebookname\").innerHTML=\"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(bprize==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tdocument.getElementById(\"ebookprize\").innerHTML=\"please enter book prize\";\r\n");
      out.write("\t     return false;\r\n");
      out.write("\t     }\r\n");
      out.write("\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tdocument.getElementById(\"ebookprize\").innerHTML=\"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\tif(bauthor==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\tdocument.getElementById(\"ebookauthor\").innerHTML=\"please enter book author\";\r\n");
      out.write("     return false;\r\n");
      out.write("     }\r\n");
      out.write("else\r\n");
      out.write("\t{\r\n");
      out.write("\tdocument.getElementById(\"ebookauthor\").innerHTML=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(bquantity==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\tdocument.getElementById(\"ebookquantity\").innerHTML=\"please enter book quantity\";\r\n");
      out.write("     return false;\r\n");
      out.write("     }\r\n");
      out.write("else\r\n");
      out.write("\t{\r\n");
      out.write("\tdocument.getElementById(\"ebookquantity\").innerHTML=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(bdesc==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\tdocument.getElementById(\"ebookdesc\").innerHTML=\"please enter  book Description\";\r\n");
      out.write("     return false;\r\n");
      out.write("     }\r\n");
      out.write("else\r\n");
      out.write("\t{\r\n");
      out.write("\tdocument.getElementById(\"ebookdesc\").innerHTML=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t}</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<form onsubmit=\"return validate()\" action=\"BookServlet\" method=\"post\" >\r\n");
      out.write("<h1><u><b>Update Book Details</b></u></h1>\r\n");
Book book=(Book)session.getAttribute("bookId"); 
      out.write("\r\n");
      out.write("<table  bOrders=\"2\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Enter Book id</th>\r\n");
      out.write("<th><input id=\"bookid\" type=\"text\" name=\"bookid\" value=\"");
      out.print(book.getBookId() );
      out.write("\"></th>\r\n");
      out.write("<td> <span id=\"ebookid\" style=\"color:red\" ></span></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<th>Enter Book Name</th>\r\n");
      out.write("<th><input id=\"bookname\" type=\"text\" name=\"bookname\" value=\"");
      out.print(book.getBookName() );
      out.write("\"></th>\r\n");
      out.write("<td> <span id=\"ebookname\" style=\"color:red\" ></span></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Enter Book Prize</th>\r\n");
      out.write("<th><input id=\"bookprize\" type=\"text\" name=\"bookprize\"  value=\"");
      out.print(book.getPrize() );
      out.write("\"></th>\r\n");
      out.write("<td><span id=\"ebookprize\" style=\"color:red\"></span></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Enter Book Author</th>\r\n");
      out.write("<th><input id=\"bookauthor\" type=\"text\" name=\"bookauthor\" value=\"");
      out.print(book.getAuthorName());
      out.write("\"></th>\r\n");
      out.write("<td><span id=\"ebookauthor\" style=\"color:red\"></span></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Enter Book Publisher</th>\r\n");
      out.write("<th>\r\n");
      out.write("<select name=\"publisher\" id=\"publisher\">\r\n");
      out.write("</select>\r\n");
      out.write("</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Enter Book Category</th>\r\n");
      out.write("<th>\r\n");
      out.write("<select name=\"category\" id=\"category\">\r\n");
      out.write("</select>\r\n");
      out.write("</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Enter Book Quantity</th>\r\n");
      out.write("\r\n");
      out.write("<th><input id=\"bookquantity\" type=\"text\" name=\"bookquantity\" value=\"");
      out.print(book.getQuantity() );
      out.write("\"></th>\r\n");
      out.write("<td><span id=\"ebookquantity\" style=\"color:red\"></span></td>\r\n");
      out.write("\r\n");
      out.write("</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Enter Book Description</th>\r\n");
      out.write("<th><input id=\"bookdesc\" type=\"text\" name=\"bookdesc\"  value=\"");
      out.print(book.getBookDesc() );
      out.write("\"></th>\r\n");
      out.write("<td><span id=\"ebookdesc\" style=\"color:red\"></span></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<!-- <tr>\r\n");
      out.write("<th>Book Image</th>\r\n");
      out.write("<th><input type=\"file\" size=300 name=\"bookImage\"></th>\r\n");
      out.write("\r\n");
      out.write("</tr> -->\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<th><input type=\"reset\"  value=\"Clear\" name=\"\" ></th>\r\n");
      out.write("\r\n");
      out.write("<th><input type=\"submit\" value=\"update\" name=\"action\"></th>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
